module.exports = {
    NULL_VALUE: '필요한 값이 없습니다',
    OUT_OF_VALUE: '파라미터 값이 잘못되었습니다',
    //profile
    NO_PROFILE: '프로필 값이 없습니다.',
    SUCCESS_SEARCH : "제조사를 검색 성공 했습니다",
    MISS_MATCH_PW : "로그인 정보가 일치하지 않습니다",
    ALREADY_ID : "유저가 이미 존재합니다",
    AVAILABLE_ID : "사용한 아이디 입니다",
    SUCCESS_USER : "유저를 검색 성공했습니다",
    SUCCESS_SEARCH_RATING : "평점 정렬을 성공 했습니다",
    SUCCESS_SEARCH_PREFER : "선호도 정렬을 성공 했습니다",
    NO_SEARCH : "검색한 결과가 존재하지 않습니다",
    NO_USER : "유저가 존재하지 않습니다",
    CREATED_USER : "회원가입 성공입니다",
    NO_USER_PROFILE : "해당 유저에 프로필이 없습니다",
    SUCCESS_REVIEW_DETAIL : "리뷰상세 조회성공입니다",
    SUCCESS_REVIEW_ADD : "리뷰등록",
    PERMISSION_DENIED_DELETE_POST:'삭제 권한이 없습니다',
    EMPTY_TOKEN : "토큰이 존재하지 않습니다",
    SUCCESS_PROFILE_READ : "프로필 조회성공입니다",
    PERMISSION_DENIED_UPDATE_PROFILE : "프로필 수정 권한이 없습니다",
    PERMISSION_DENIED_UPDATE_REVIEW : "리뷰 등록 권한이 없습니다",
    SUCCESS_UPDATE_PROFILE : "프로필 수정 성공입니다",
    PERMISSION_DENIED_UPDATE_POST:'수정 권한이 없습니다',
    READ_POST_SUCCESS: "게시글 조회 성공",
    READ_POST_FAIL: "게시글 조회 실패",
    CONVERSE_PROFILE_SUCCESS: "프로필 전환 성공",
    REQUEST_FOLLOW_SUCCESS: "팔로우 신청 성공",
    READ_FOLLOW_LIST_SUCCESS : "팔로우 목록 조회 성공",
    READ_FOLLOWER_LIST_SUCCESS : "팔로워 목록 조회 성공",
    DELETE_FOLLOW_SUCCESS: "팔로우 취소 성공",
    READ_RECOMMEND_SUCCESS:"추천 리스트 조회 성공",
    EXCEEDED_PROFILE_NUMBER: "프로필 등록 횟수 초과",
    ADD_REVIEW_SUCCESS: '리뷰 추가 성공'
};
